version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      args:
        - TEST_SUITE=${TEST_SUITE}
        - OPENCART=${OPENCART}
        - SERVER_PORT=${SERVER_PORT}
        - OC_DB_HOSTNAME=${OC_DB_HOSTNAME}
        - OC_DB_USERNAME=${OC_DB_USERNAME}
        - OC_DB_PASSWORD=${OC_DB_PASSWORD}
        - OC_DB_DATABASE=${OC_DB_DATABASE}
        - OC_USERNAME=${OC_USERNAME}
        - OC_PASSWORD=${OC_PASSWORD}
        - OC_EMAIL=${OC_EMAIL}
    volumes:
      - ./:/oc_shipping_area
    links:
      - "mysql"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mysql
    env_file:
      - .env
    working_dir: /oc_shipping_area
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${OC_DB_DATABASE}
      - MYSQL_USER=${OC_DB_USERNAME}
      - MYSQL_PASSWORD=${OC_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"