name: release-master
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          default_bump: "minor"
          release_branches : "main,develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'oc_shipping_area.ocmod.zip'
          directory: 'src'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}     
          artifacts: "oc_shipping_area.ocmod.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
        
